POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "usernameTest1",
    "password": "superSafePassword"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "blogs": [],
    "username": "usernameTest1",
    "name": "nameTest1",
    "password": "superSafePassword"
}

###
GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/619c82d279f51053561727c2

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lVGVzdDEiLCJpZCI6IjYyZGY3OGIxZDQ0YzU2M2UzMDk2Mzk0MiIsImlhdCI6MTY2MTEzODMyMCwiZXhwIjoxNjYxMTk4MzIwfQ.0j3uYXadHm2VwdQdQrzYnVw-NhuntneROh5grnr_JHM

{
    "title": "Testing 343",
    "author": "yuup",
    "url": "noooo"
}

###
PUT http://localhost:3003/api/blogs/6302f63d89d377464246afbb
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lVGVzdDEiLCJpZCI6IjYyZGY3OGIxZDQ0YzU2M2UzMDk2Mzk0MiIsImlhdCI6MTY2MTEzODMyMCwiZXhwIjoxNjYxMTk4MzIwfQ.0j3uYXadHm2VwdQdQrzYnVw-NhuntneROh5grnr_JHM

{
    "title": "New type of update",
    "author": "update shit",
    "url": "update test"
}

###
DELETE http://localhost:3003/api/blogs/6302f63d89d377464246afbb
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lVGVzdDEiLCJpZCI6IjYyZGY3OGIxZDQ0YzU2M2UzMDk2Mzk0MiIsImlhdCI6MTY2MTEzODMyMCwiZXhwIjoxNjYxMTk4MzIwfQ.0j3uYXadHm2VwdQdQrzYnVw-NhuntneROh5grnr_JHM

###
DELETE http://localhost:3003/api/users/61fdb79232a16f62f45316bc

###
POST http://localhost:3003/api/blogs/63000dc3858eec64703a07a1/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lVGVzdDEiLCJpZCI6IjYyZGY3OGIxZDQ0YzU2M2UzMDk2Mzk0MiIsImlhdCI6MTY2MDk0Nzg5NCwiZXhwIjoxNjYxMDA3ODk0fQ.j1PoKwZmqqAkpj4PhE4tzVL3bCjtvJT__3L8ShNquJE

{
    "comment": "Testing comment saved to blog"
}

###
POST http://localhost:3003/api/blogs/63000dc3858eec64703a07a1/likes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lVGVzdDEiLCJpZCI6IjYyZGY3OGIxZDQ0YzU2M2UzMDk2Mzk0MiIsImlhdCI6MTY2MTEwODY4MiwiZXhwIjoxNjYxMTY4NjgyfQ.in4aKj5K7SHw0uf2_W2dKaBF4jxOjlxpoczs1ob8azs
